import Foundation
import SwiftUI

enum AppLanguage: String, CaseIterable, Identifiable {
    case english = "en"
    case dutch = "nl"
    case german = "de"
    case french = "fr"

    var id: String { rawValue }

    var nativeName: String {
        switch self {
        case .english: return "English"
        case .dutch: return "Nederlands"
        case .german: return "Deutsch"
        case .french: return "Français"
        }
    }

    var code: String { rawValue.uppercased() }
}

final class Localization: ObservableObject {
    static let shared = Localization()
    private static let defaultsKey = "appLanguage"

    @Published var language: AppLanguage {
        didSet { UserDefaults.standard.set(language.rawValue, forKey: Self.defaultsKey) }
    }

    init() {
        if let raw = UserDefaults.standard.string(forKey: Self.defaultsKey),
           let stored = AppLanguage(rawValue: raw) {
            language = stored
        } else {
            language = .english
        }
    }

    func t(_ key: String) -> String {
        Self.tables[language]?[key] ?? Self.tables[.english]?[key] ?? key
    }

    func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: t(key), arguments: args)
    }

    private static let tables: [AppLanguage: [String: String]] = [
        .english: english,
        .dutch: dutch,
        .german: german,
        .french: french
    ]
}

enum L10n {
    static func t(_ key: String) -> String { Localization.shared.t(key) }
    static func t(_ key: String, _ args: CVarArg...) -> String {
        String(format: Localization.shared.t(key), arguments: args)
    }
}

private let english: [String: String] = [
    "header.chooseMode": "Which kind of QLab workspace do you want to check?",
    "mode.section": "Project type",
    "mode.headline": "How does QLab handle media?",
    "mode.intro": "Pick the setting that matches this workspace. Then choose the .qlab5 file or the project folder, and for loose references the content folders too.",
    "mode.bundled.title": "Files in project folder",
    "mode.bundled.body": "Media lives in collection folders next to the workspace, usually audio and video. Choose the .qlab5 or the project folder; backups are skipped.",
    "mode.bundled.qlab": "Copy files into project folder",
    "mode.external.title": "Loose references",
    "mode.external.body": "The workspace points at files where they already are. You pick one or more folders to search in.",
    "mode.external.qlab": "Do not copy files",
    "mode.choose": "Choose this type",
    "mode.other": "Different project type",
    "mode.switch": "Switch",
    "mode.suggest": "The QLab setting points to %@. You can switch; your current choice stays until you do.",
    "mode.mismatch.bundled": "QLab has “Copy files into project folder” turned off in this workspace. Check whether loose references is a better fit.",
    "mode.mismatch.external": "QLab copies files into the project folder in this workspace. Check whether the other mode is a better fit.",

    "workspace.title": "QLab workspace",
    "workspace.multiple": "This folder contains more than one workspace. Choose which one to check.",
    "workspace.drop.bundled": "Drop the .qlab5 or the project folder here",
    "workspace.drop.external": "Drop the .qlab5 file here",
    "workspace.drop.bundledHint": "The project folder holds the workspace and the audio and video folders. The app finds those folders itself.",
    "workspace.drop.externalHint": "Then choose one or more folders where the media lives.",
    "workspace.pickFile": "Choose .qlab5",
    "workspace.pickFolder": "Choose project folder",
    "workspace.pickFileMessage": "Choose the QLab 5 workspace file",
    "workspace.pickFolderMessage": "Choose the project folder: it contains the .qlab5 and the content folders",
    "workspace.needFirst": "Choose the .qlab5 or the project folder first. Then the app shows the folders beside it, without backups.",
    "workspace.noneFound": "No audio, video or other content folders found next to this workspace.",
    "workspace.pickContent": "Choose content folder",
    "workspace.pickContentMessage": "Choose one or more folders with audio, video or images",
    "workspace.addFolders": "Add one or more folders that contain audio, video and images.",
    "workspace.reading": "Reading workspace…",
    "workspace.mediaCount": "%d media files in %@",
    "workspace.noneChosen": "No workspace chosen yet",
    "workspace.needWorkspace": "Choose a QLab workspace first.",
    "workspace.needFolder": "Add at least one content folder.",

    "folders.found": "Found content folders",
    "folders.content": "Content folders",
    "folders.protectedExt": "Protected extensions",
    "folders.protectedPlaceholder": "e.g. wav, png — unused files with these extensions are kept",
    "folders.protect": "Protect this folder",
    "folders.protectedHelp": "This folder is locked: unused files here are not moved to the Trash",
    "folders.far": "“%@” is not near the workspace. Check that this is the right content folder, especially before deleting.",
    "folders.large": "“%@” is large (%d files, %@). Scanning or cleaning can take a while or touch too much by accident.",

    "qlab.open": "This workspace is open in QLab. You can analyse; deleting is blocked until you close the show.",
    "qlab.running": "QLab is running. Close the workspace before moving files to the Trash.",
    "qlab.blocksTrash": "QLab has this workspace open. Close the show first.",

    "error.invalidArchive": "This is not a valid QLab 5 workspace file.",
    "error.unreadable": "The QLab file could not be read.",
    "error.noWorkspace": "There is no .qlab5 file in this folder.",
    "error.multipleWorkspaces": "This folder contains more than one QLab workspace. Choose one: %@.",

    "results.show": "Show overview",
    "results.back": "Edit",
    "results.new": "New analysis",
    "results.ignoreDisarmed": "Ignore disarmed cues",
    "results.includeBackups": "Include backups",
    "results.includeBackupsHelp": "Also read .qlab5backup files next to the show. Media folders named backups stay skipped.",
    "results.sort": "Sort",
    "results.sort.name": "Name",
    "results.sort.kind": "Type",
    "results.sort.date": "Date",
    "results.sort.size": "Size",
    "results.search": "Search by file, cue number or cue name",
    "results.used": "In use",
    "results.unused": "Not in use",
    "results.missing": "Missing",
    "results.usedEmpty": "No used files",
    "results.unusedEmpty": "Nothing to clean up",
    "results.missingEmpty": "No missing targets",
    "results.backupOnly": "Only in backup",
    "results.backupOnlyEmpty": "Nothing only in backups",
    "results.backupOnlyEmptyBody": "Every file from the backups is also in the current workspace.",
    "results.backupOnlyNone": "No backup files",
    "results.backupOnlyNoneBody": "No .qlab5backup files were found next to this workspace.",
    "results.backupOnlyNoHits": "No matches in backup-only files.",
    "results.usedEmptyBody": "The workspace does not reference files in the chosen folders.",
    "results.unusedEmptyBody": "Every scanned file is used by QLab.",
    "results.missingEmptyBody": "Every QLab reference is in the scanned folders.",
    "results.usedNoHits": "No matches in used files.",
    "results.unusedNoHits": "No matches in unused files.",
    "results.missingNoHits": "No matches in missing files.",
    "results.totalScanned": "In folders",
    "results.totalUsed": "In use",
    "results.totalUnused": "Can go",
    "results.totalProtected": "Protected",
    "results.copyAll": "Copy all paths",
    "results.trash": "Move to Trash",
    "results.copyPath": "Copy path",
    "results.reveal": "Show in Finder",
    "results.selectHelp": "Click to select, space bar for Quick Look",
    "results.usageHelp": "Times used in the QLab workspace",
    "results.duplicate": "Same name as %@",
    "results.duplicates": "Duplicates",
    "results.totalBackups": "Backups",
    "results.trashOne": "Move 1 file to the Trash?",
    "results.trashMany": "Move %d files to the Trash?",
    "results.trashInfo": "Together %@. Only files on disk go to the Trash; cues in QLab stay.",
    "results.cancel": "Cancel",

    "kind.audio": "Audio",
    "kind.video": "Video",
    "kind.image": "Images",
    "kind.midi": "MIDI",
    "kind.other": "Other",
    "kind.file": "File",

    "recents.title": "Recent workspaces",
    "recents.missing": "That workspace is no longer on disk.",
    "recents.remove": "Remove from recents",

    "about.title": "About",
    "about.close": "Close",
    "about.coffee": "Buy me a coffee",
    "about.github": "GitHub releases",

    "progress.scanning": "Scanning folders… %d files",
    "progress.matching": "Matching %d files to the workspace…",
    "progress.hashing": "Checking possible duplicates… %d files",
    "progress.backups": "Reading backups… %d files",
    "backups.parseFailed": "Could not read backup “%@”.",

    "language.label": "Language"
]

private let dutch: [String: String] = [
    "header.chooseMode": "Welke soort QLab-workspace wil je controleren?",
    "mode.section": "Projecttype",
    "mode.headline": "Hoe gaat QLab met media om?",
    "mode.intro": "Kies de instelling die bij deze workspace hoort. Daarna kies je de .qlab5-file of de projectmap, en bij losse verwijzingen ook de contentmappen.",
    "mode.bundled.title": "Bestanden in projectmap",
    "mode.bundled.body": "Media staat in verzamelmappen naast de workspace, meestal audio en video. Je kiest de .qlab5 of de projectmap; backups worden overgeslagen.",
    "mode.bundled.qlab": "Copy files into project folder",
    "mode.external.title": "Losse verwijzingen",
    "mode.external.body": "De workspace verwijst naar bestaande files. Jij kiest zelf één of meer mappen waarin we zoeken.",
    "mode.external.qlab": "Bestanden niet kopiëren",
    "mode.choose": "Kies dit type",
    "mode.other": "Ander projecttype",
    "mode.switch": "Overschakelen",
    "mode.suggest": "QLab-instelling wijst op %@. Je kunt overschakelen; je huidige keuze blijft tot je dat doet.",
    "mode.mismatch.bundled": "QLab heeft in deze workspace ‘Copy files into project folder’ uitstaan. Controleer of losse verwijzingen beter past.",
    "mode.mismatch.external": "QLab kopieert in deze workspace bestanden naar de projectmap. Controleer of de andere modus beter past.",

    "workspace.title": "QLab workspace",
    "workspace.multiple": "Deze map bevat meerdere workspaces. Kies welke je wilt controleren.",
    "workspace.drop.bundled": "Sleep de .qlab5 of de projectmap hierheen",
    "workspace.drop.external": "Sleep de .qlab5-file hierheen",
    "workspace.drop.bundledHint": "In de projectmap staan de workspace en de audio- en videomappen. De app vindt die mappen zelf.",
    "workspace.drop.externalHint": "Kies daarna één of meer mappen waarin de media staat.",
    "workspace.pickFile": "Kies .qlab5",
    "workspace.pickFolder": "Kies projectmap",
    "workspace.pickFileMessage": "Kies het QLab 5 workspace-bestand",
    "workspace.pickFolderMessage": "Kies de projectmap: daarin staan de .qlab5 en de contentmappen",
    "workspace.needFirst": "Kies eerst de .qlab5 of de projectmap. Daarna toont de app de mappen ernaast, zonder backups.",
    "workspace.noneFound": "Geen audio-, video- of andere contentmappen gevonden naast deze workspace.",
    "workspace.pickContent": "Kies contentmap",
    "workspace.pickContentMessage": "Kies één of meer mappen met audio, video of images",
    "workspace.addFolders": "Voeg één of meer mappen toe waarin audio, video en images staan.",
    "workspace.reading": "Workspace lezen…",
    "workspace.mediaCount": "%d mediabestanden in %@",
    "workspace.noneChosen": "Nog geen workspace gekozen",
    "workspace.needWorkspace": "Kies eerst een QLab-workspace.",
    "workspace.needFolder": "Voeg minstens één contentmap toe.",

    "folders.found": "Gevonden contentmappen",
    "folders.content": "Contentmappen",
    "folders.protectedExt": "Beschermde extensies",
    "folders.protectedPlaceholder": "bijv. wav, png — ongebruikte files met deze extensie blijven staan",
    "folders.protect": "Bescherm deze map",
    "folders.protectedHelp": "Map is beschermd: ongebruikte files hierin gaan niet naar de prullenmand",
    "folders.far": "‘%@’ ligt buiten de buurt van de workspace. Controleren of dit de juiste contentmap is, vooral vóór verwijderen.",
    "folders.large": "‘%@’ is groot (%d bestanden, %@). Scannen of opruimen kan lang duren of per ongeluk te veel raken.",

    "qlab.open": "Deze workspace staat open in QLab. Analyseren mag, verwijderen is geblokkeerd tot je de show sluit.",
    "qlab.running": "QLab draait. Sluit de workspace voordat je bestanden naar de prullenmand zet.",
    "qlab.blocksTrash": "QLab heeft deze workspace open. Sluit de show eerst.",

    "error.invalidArchive": "Dit is geen geldig QLab 5 workspace-bestand.",
    "error.unreadable": "Het QLab-bestand kon niet worden gelezen.",
    "error.noWorkspace": "In deze map staat geen .qlab5-bestand.",
    "error.multipleWorkspaces": "Deze map bevat meerdere QLab-workspaces. Kies er één: %@.",

    "results.show": "Toon overzicht",
    "results.back": "Aanpassen",
    "results.new": "Nieuwe analyse",
    "results.ignoreDisarmed": "Negeer gedisarmde cues",
    "results.includeBackups": "Lees backups mee",
    "results.includeBackupsHelp": "Lees ook .qlab5backup-bestanden naast de show. Mappen die backups heten blijven overgeslagen als media.",
    "results.sort": "Sorteren",
    "results.sort.name": "Naam",
    "results.sort.kind": "Type",
    "results.sort.date": "Datum",
    "results.sort.size": "Grootte",
    "results.search": "Zoek op bestand, cue-nummer of cue-naam",
    "results.used": "In gebruik",
    "results.unused": "Niet in gebruik",
    "results.missing": "Ontbreekt",
    "results.usedEmpty": "Geen gebruikte bestanden",
    "results.unusedEmpty": "Niets om op te ruimen",
    "results.missingEmpty": "Geen ontbrekende targets",
    "results.backupOnly": "Alleen in backup",
    "results.backupOnlyEmpty": "Niets alleen in backups",
    "results.backupOnlyEmptyBody": "Elk bestand uit de backups zit ook in de huidige workspace.",
    "results.backupOnlyNone": "Geen backupbestanden",
    "results.backupOnlyNoneBody": "Er staan geen .qlab5backup-bestanden naast deze workspace.",
    "results.backupOnlyNoHits": "Geen treffers bij alleen-in-backup.",
    "results.usedEmptyBody": "De workspace verwijst niet naar bestanden in de gekozen mappen.",
    "results.unusedEmptyBody": "Alle gescande bestanden worden door QLab gebruikt.",
    "results.missingEmptyBody": "Alle QLab-verwijzingen staan in de gescande mappen.",
    "results.usedNoHits": "Geen treffers in de gebruikte bestanden.",
    "results.unusedNoHits": "Geen treffers in de ongebruikte bestanden.",
    "results.missingNoHits": "Geen treffers bij ontbrekende bestanden.",
    "results.totalScanned": "In mappen",
    "results.totalUsed": "In gebruik",
    "results.totalUnused": "Mag weg",
    "results.totalProtected": "Beschermd",
    "results.copyAll": "Kopieer alle paden",
    "results.trash": "Naar prullenmand",
    "results.copyPath": "Kopieer pad",
    "results.reveal": "Toon in Finder",
    "results.selectHelp": "Klik om te selecteren, spatie voor voorvertoning",
    "results.usageHelp": "Aantal keren gebruikt in de QLab-workspace",
    "results.duplicate": "Dezelfde naam als %@",
    "results.duplicates": "Duplicaten",
    "results.totalBackups": "Backups",
    "results.trashOne": "1 bestand naar de prullenmand?",
    "results.trashMany": "%d bestanden naar de prullenmand?",
    "results.trashInfo": "Samen %@. Alleen files op schijf gaan naar de prullenmand; cues in QLab blijven staan.",
    "results.cancel": "Annuleren",

    "kind.audio": "Audio",
    "kind.video": "Video",
    "kind.image": "Images",
    "kind.midi": "MIDI",
    "kind.other": "Overig",
    "kind.file": "Bestand",

    "recents.title": "Recente workspaces",
    "recents.missing": "Die workspace staat niet meer op schijf.",
    "recents.remove": "Verwijder uit recent",

    "about.title": "Over",
    "about.close": "Sluiten",
    "about.coffee": "Buy me a coffee",
    "about.github": "GitHub-releases",

    "progress.scanning": "Mappen scannen… %d bestanden",
    "progress.matching": "%d bestanden koppelen aan de workspace…",
    "progress.hashing": "Mogelijke duplicaten controleren… %d bestanden",
    "progress.backups": "Backups lezen… %d bestanden",
    "backups.parseFailed": "Backup “%@” kon niet worden gelezen.",

    "language.label": "Taal"
]

private let german: [String: String] = [
    "header.chooseMode": "Welche Art QLab-Workspace möchtest du prüfen?",
    "mode.section": "Projekttyp",
    "mode.headline": "Wie geht QLab mit Medien um?",
    "mode.intro": "Wähle die Einstellung, die zu diesem Workspace passt. Danach die .qlab5-Datei oder den Projektordner, und bei losen Verweisen auch die Content-Ordner.",
    "mode.bundled.title": "Dateien im Projektordner",
    "mode.bundled.body": "Medien liegen in Sammelordnern neben dem Workspace, meist audio und video. Wähle die .qlab5 oder den Projektordner; Backups werden übersprungen.",
    "mode.bundled.qlab": "Copy files into project folder",
    "mode.external.title": "Lose Verweise",
    "mode.external.body": "Der Workspace zeigt auf bestehende Dateien. Du wählst einen oder mehrere Ordner zum Durchsuchen.",
    "mode.external.qlab": "Dateien nicht kopieren",
    "mode.choose": "Diesen Typ wählen",
    "mode.other": "Anderer Projekttyp",
    "mode.switch": "Wechseln",
    "mode.suggest": "Die QLab-Einstellung deutet auf %@. Du kannst wechseln; deine aktuelle Wahl bleibt, bis du das tust.",
    "mode.mismatch.bundled": "In diesem Workspace ist „Copy files into project folder“ aus. Prüfe, ob lose Verweise besser passen.",
    "mode.mismatch.external": "QLab kopiert in diesem Workspace Dateien in den Projektordner. Prüfe, ob der andere Modus besser passt.",

    "workspace.title": "QLab-Workspace",
    "workspace.multiple": "Dieser Ordner enthält mehrere Workspaces. Wähle, welchen du prüfen willst.",
    "workspace.drop.bundled": "Lege die .qlab5 oder den Projektordner hier ab",
    "workspace.drop.external": "Lege die .qlab5-Datei hier ab",
    "workspace.drop.bundledHint": "Im Projektordner liegen Workspace sowie Audio- und Videoordner. Die App findet diese Ordner selbst.",
    "workspace.drop.externalHint": "Wähle danach einen oder mehrere Ordner mit den Medien.",
    "workspace.pickFile": ".qlab5 wählen",
    "workspace.pickFolder": "Projektordner wählen",
    "workspace.pickFileMessage": "QLab-5-Workspace-Datei wählen",
    "workspace.pickFolderMessage": "Projektordner wählen: darin liegen die .qlab5 und die Content-Ordner",
    "workspace.needFirst": "Wähle zuerst die .qlab5 oder den Projektordner. Danach zeigt die App die Ordner daneben, ohne Backups.",
    "workspace.noneFound": "Keine Audio-, Video- oder anderen Content-Ordner neben diesem Workspace gefunden.",
    "workspace.pickContent": "Content-Ordner wählen",
    "workspace.pickContentMessage": "Einen oder mehrere Ordner mit Audio, Video oder Bildern wählen",
    "workspace.addFolders": "Füge einen oder mehrere Ordner mit Audio, Video und Bildern hinzu.",
    "workspace.reading": "Workspace wird gelesen…",
    "workspace.mediaCount": "%d Mediendateien in %@",
    "workspace.noneChosen": "Noch kein Workspace gewählt",
    "workspace.needWorkspace": "Wähle zuerst einen QLab-Workspace.",
    "workspace.needFolder": "Füge mindestens einen Content-Ordner hinzu.",

    "folders.found": "Gefundene Content-Ordner",
    "folders.content": "Content-Ordner",
    "folders.protectedExt": "Geschützte Endungen",
    "folders.protectedPlaceholder": "z. B. wav, png — ungenutzte Dateien mit diesen Endungen bleiben",
    "folders.protect": "Diesen Ordner schützen",
    "folders.protectedHelp": "Ordner ist gesperrt: ungenutzte Dateien hier landen nicht im Papierkorb",
    "folders.far": "„%@“ liegt nicht in der Nähe des Workspace. Prüfen, ob das der richtige Content-Ordner ist, besonders vor dem Löschen.",
    "folders.large": "„%@“ ist groß (%d Dateien, %@). Scannen oder Aufräumen kann dauern oder versehentlich zu viel treffen.",

    "qlab.open": "Dieser Workspace ist in QLab geöffnet. Analysieren geht; Löschen ist gesperrt, bis du die Show schließt.",
    "qlab.running": "QLab läuft. Schließe den Workspace, bevor Dateien in den Papierkorb gehen.",
    "qlab.blocksTrash": "QLab hat diesen Workspace geöffnet. Schließe die Show zuerst.",

    "error.invalidArchive": "Das ist keine gültige QLab-5-Workspace-Datei.",
    "error.unreadable": "Die QLab-Datei konnte nicht gelesen werden.",
    "error.noWorkspace": "In diesem Ordner liegt keine .qlab5-Datei.",
    "error.multipleWorkspaces": "Dieser Ordner enthält mehrere QLab-Workspaces. Wähle einen: %@.",

    "results.show": "Übersicht zeigen",
    "results.back": "Anpassen",
    "results.new": "Neue Analyse",
    "results.ignoreDisarmed": "Deaktivierte Cues ignorieren",
    "results.includeBackups": "Backups mitlesen",
    "results.includeBackupsHelp": "Liest auch .qlab5backup-Dateien neben der Show. Ordner namens Backups bleiben als Medien übersprungen.",
    "results.sort": "Sortieren",
    "results.sort.name": "Name",
    "results.sort.kind": "Typ",
    "results.sort.date": "Datum",
    "results.sort.size": "Größe",
    "results.search": "Suche nach Datei, Cue-Nummer oder Cue-Name",
    "results.used": "In Gebrauch",
    "results.unused": "Nicht in Gebrauch",
    "results.missing": "Fehlt",
    "results.usedEmpty": "Keine verwendeten Dateien",
    "results.unusedEmpty": "Nichts zum Aufräumen",
    "results.missingEmpty": "Keine fehlenden Targets",
    "results.backupOnly": "Nur im Backup",
    "results.backupOnlyEmpty": "Nichts nur in Backups",
    "results.backupOnlyEmptyBody": "Jede Datei aus den Backups ist auch im aktuellen Workspace.",
    "results.backupOnlyNone": "Keine Backup-Dateien",
    "results.backupOnlyNoneBody": "Neben diesem Workspace liegen keine .qlab5backup-Dateien.",
    "results.backupOnlyNoHits": "Keine Treffer bei nur-im-Backup.",
    "results.usedEmptyBody": "Der Workspace verweist nicht auf Dateien in den gewählten Ordnern.",
    "results.unusedEmptyBody": "Alle gescannten Dateien werden von QLab verwendet.",
    "results.missingEmptyBody": "Alle QLab-Verweise liegen in den gescannten Ordnern.",
    "results.usedNoHits": "Keine Treffer bei verwendeten Dateien.",
    "results.unusedNoHits": "Keine Treffer bei ungenutzten Dateien.",
    "results.missingNoHits": "Keine Treffer bei fehlenden Dateien.",
    "results.totalScanned": "In Ordnern",
    "results.totalUsed": "In Gebrauch",
    "results.totalUnused": "Kann weg",
    "results.totalProtected": "Geschützt",
    "results.copyAll": "Alle Pfade kopieren",
    "results.trash": "In den Papierkorb",
    "results.copyPath": "Pfad kopieren",
    "results.reveal": "Im Finder zeigen",
    "results.selectHelp": "Klicken zum Auswählen, Leertaste für Quick Look",
    "results.usageHelp": "Wie oft im QLab-Workspace verwendet",
    "results.duplicate": "Gleicher Name wie %@",
    "results.duplicates": "Duplikate",
    "results.totalBackups": "Backups",
    "results.trashOne": "1 Datei in den Papierkorb?",
    "results.trashMany": "%d Dateien in den Papierkorb?",
    "results.trashInfo": "Zusammen %@. Nur Dateien auf der Platte gehen in den Papierkorb; Cues in QLab bleiben.",
    "results.cancel": "Abbrechen",

    "kind.audio": "Audio",
    "kind.video": "Video",
    "kind.image": "Bilder",
    "kind.midi": "MIDI",
    "kind.other": "Sonstiges",
    "kind.file": "Datei",

    "recents.title": "Zuletzt geöffnet",
    "recents.missing": "Dieser Workspace liegt nicht mehr auf der Platte.",
    "recents.remove": "Aus der Liste entfernen",

    "about.title": "Über",
    "about.close": "Schließen",
    "about.coffee": "Buy me a coffee",
    "about.github": "GitHub-Releases",

    "progress.scanning": "Ordner werden gelesen… %d Dateien",
    "progress.matching": "%d Dateien werden dem Workspace zugeordnet…",
    "progress.hashing": "Mögliche Duplikate prüfen… %d Dateien",
    "progress.backups": "Backups werden gelesen… %d Dateien",
    "backups.parseFailed": "Backup “%@” konnte nicht gelesen werden.",

    "language.label": "Sprache"
]

private let french: [String: String] = [
    "header.chooseMode": "Quel type d’espace de travail QLab voulez-vous vérifier ?",
    "mode.section": "Type de projet",
    "mode.headline": "Comment QLab gère-t-il les médias ?",
    "mode.intro": "Choisissez le réglage qui correspond à cet espace. Ensuite le fichier .qlab5 ou le dossier projet, et pour les références libres les dossiers de contenu aussi.",
    "mode.bundled.title": "Fichiers dans le dossier projet",
    "mode.bundled.body": "Les médias sont dans des dossiers à côté de l’espace de travail, souvent audio et video. Choisissez le .qlab5 ou le dossier projet ; les sauvegardes sont ignorées.",
    "mode.bundled.qlab": "Copy files into project folder",
    "mode.external.title": "Références libres",
    "mode.external.body": "L’espace pointe vers des fichiers déjà en place. Vous choisissez un ou plusieurs dossiers à parcourir.",
    "mode.external.qlab": "Ne pas copier les fichiers",
    "mode.choose": "Choisir ce type",
    "mode.other": "Autre type de projet",
    "mode.switch": "Changer",
    "mode.suggest": "Le réglage QLab indique %@. Vous pouvez changer ; le choix actuel reste jusqu’à ce que vous le fassiez.",
    "mode.mismatch.bundled": "« Copy files into project folder » est désactivé dans cet espace. Vérifiez si les références libres conviennent mieux.",
    "mode.mismatch.external": "QLab copie les fichiers dans le dossier projet. Vérifiez si l’autre mode convient mieux.",

    "workspace.title": "Espace QLab",
    "workspace.multiple": "Ce dossier contient plusieurs espaces. Choisissez celui à vérifier.",
    "workspace.drop.bundled": "Déposez le .qlab5 ou le dossier projet ici",
    "workspace.drop.external": "Déposez le fichier .qlab5 ici",
    "workspace.drop.bundledHint": "Le dossier projet contient l’espace et les dossiers audio et vidéo. L’app les trouve elle-même.",
    "workspace.drop.externalHint": "Choisissez ensuite un ou plusieurs dossiers où se trouvent les médias.",
    "workspace.pickFile": "Choisir .qlab5",
    "workspace.pickFolder": "Choisir le dossier projet",
    "workspace.pickFileMessage": "Choisir le fichier d’espace QLab 5",
    "workspace.pickFolderMessage": "Choisir le dossier projet : il contient le .qlab5 et les dossiers de contenu",
    "workspace.needFirst": "Choisissez d’abord le .qlab5 ou le dossier projet. L’app affiche ensuite les dossiers à côté, sans sauvegardes.",
    "workspace.noneFound": "Aucun dossier audio, vidéo ou autre contenu trouvé à côté de cet espace.",
    "workspace.pickContent": "Choisir un dossier de contenu",
    "workspace.pickContentMessage": "Choisir un ou plusieurs dossiers avec audio, vidéo ou images",
    "workspace.addFolders": "Ajoutez un ou plusieurs dossiers contenant audio, vidéo et images.",
    "workspace.reading": "Lecture de l’espace…",
    "workspace.mediaCount": "%d fichiers médias dans %@",
    "workspace.noneChosen": "Aucun espace choisi",
    "workspace.needWorkspace": "Choisissez d’abord un espace QLab.",
    "workspace.needFolder": "Ajoutez au moins un dossier de contenu.",

    "folders.found": "Dossiers de contenu trouvés",
    "folders.content": "Dossiers de contenu",
    "folders.protectedExt": "Extensions protégées",
    "folders.protectedPlaceholder": "ex. wav, png — les fichiers inutilisés avec ces extensions sont conservés",
    "folders.protect": "Protéger ce dossier",
    "folders.protectedHelp": "Dossier verrouillé : les fichiers inutilisés ici n’iront pas à la corbeille",
    "folders.far": "« %@ » n’est pas près de l’espace. Vérifiez que c’est le bon dossier de contenu, surtout avant de supprimer.",
    "folders.large": "« %@ » est volumineux (%d fichiers, %@). L’analyse ou le nettoyage peut durer ou toucher trop de fichiers.",

    "qlab.open": "Cet espace est ouvert dans QLab. L’analyse est possible ; la suppression est bloquée tant que le spectacle n’est pas fermé.",
    "qlab.running": "QLab est ouvert. Fermez l’espace avant d’envoyer des fichiers à la corbeille.",
    "qlab.blocksTrash": "QLab a cet espace ouvert. Fermez d’abord le spectacle.",

    "error.invalidArchive": "Ce n’est pas un fichier d’espace QLab 5 valide.",
    "error.unreadable": "Le fichier QLab n’a pas pu être lu.",
    "error.noWorkspace": "Il n’y a pas de fichier .qlab5 dans ce dossier.",
    "error.multipleWorkspaces": "Ce dossier contient plusieurs espaces QLab. Choisissez-en un : %@.",

    "results.show": "Afficher l’aperçu",
    "results.back": "Modifier",
    "results.new": "Nouvelle analyse",
    "results.ignoreDisarmed": "Ignorer les cues désarmées",
    "results.includeBackups": "Inclure les sauvegardes",
    "results.includeBackupsHelp": "Lit aussi les fichiers .qlab5backup à côté du spectacle. Les dossiers nommés backups restent ignorés comme médias.",
    "results.sort": "Trier",
    "results.sort.name": "Nom",
    "results.sort.kind": "Type",
    "results.sort.date": "Date",
    "results.sort.size": "Taille",
    "results.search": "Rechercher fichier, numéro ou nom de cue",
    "results.used": "Utilisé",
    "results.unused": "Non utilisé",
    "results.missing": "Manquant",
    "results.usedEmpty": "Aucun fichier utilisé",
    "results.unusedEmpty": "Rien à ranger",
    "results.missingEmpty": "Aucune cible manquante",
    "results.backupOnly": "Uniquement en sauvegarde",
    "results.backupOnlyEmpty": "Rien uniquement en sauvegarde",
    "results.backupOnlyEmptyBody": "Chaque fichier des sauvegardes est aussi dans l’espace actuel.",
    "results.backupOnlyNone": "Aucun fichier de sauvegarde",
    "results.backupOnlyNoneBody": "Aucun fichier .qlab5backup n’a été trouvé à côté de cet espace.",
    "results.backupOnlyNoHits": "Aucun résultat parmi les fichiers uniquement en sauvegarde.",
    "results.usedEmptyBody": "L’espace ne pointe vers aucun fichier dans les dossiers choisis.",
    "results.unusedEmptyBody": "Tous les fichiers scannés sont utilisés par QLab.",
    "results.missingEmptyBody": "Toutes les références QLab sont dans les dossiers scannés.",
    "results.usedNoHits": "Aucun résultat dans les fichiers utilisés.",
    "results.unusedNoHits": "Aucun résultat dans les fichiers non utilisés.",
    "results.missingNoHits": "Aucun résultat parmi les fichiers manquants.",
    "results.totalScanned": "Dans les dossiers",
    "results.totalUsed": "Utilisé",
    "results.totalUnused": "Peut partir",
    "results.totalProtected": "Protégé",
    "results.copyAll": "Copier tous les chemins",
    "results.trash": "Mettre à la corbeille",
    "results.copyPath": "Copier le chemin",
    "results.reveal": "Afficher dans le Finder",
    "results.selectHelp": "Cliquer pour sélectionner, espace pour Aperçu rapide",
    "results.usageHelp": "Nombre d’utilisations dans l’espace QLab",
    "results.duplicate": "Même nom que %@",
    "results.duplicates": "Doublons",
    "results.totalBackups": "Sauvegardes",
    "results.trashOne": "Mettre 1 fichier à la corbeille ?",
    "results.trashMany": "Mettre %d fichiers à la corbeille ?",
    "results.trashInfo": "Ensemble %@. Seuls les fichiers sur disque vont à la corbeille ; les cues QLab restent.",
    "results.cancel": "Annuler",

    "kind.audio": "Audio",
    "kind.video": "Vidéo",
    "kind.image": "Images",
    "kind.midi": "MIDI",
    "kind.other": "Autre",
    "kind.file": "Fichier",

    "recents.title": "Espaces récents",
    "recents.missing": "Cet espace n’est plus sur le disque.",
    "recents.remove": "Retirer des récents",

    "about.title": "À propos",
    "about.close": "Fermer",
    "about.coffee": "Buy me a coffee",
    "about.github": "Versions GitHub",

    "progress.scanning": "Lecture des dossiers… %d fichiers",
    "progress.matching": "Correspondance de %d fichiers avec l’espace…",
    "progress.hashing": "Vérification des doublons possibles… %d fichiers",
    "progress.backups": "Lecture des sauvegardes… %d fichiers",
    "backups.parseFailed": "Impossible de lire la sauvegarde « %@ ».",

    "language.label": "Langue"
]
